---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Understanding and using Automation controller"
      solveButton: false
    - name: module-02
      label: "Retrieve Azure cloud information"
      solveButton: false
    - name: module-03
      label: "Creating Dynamic Documentation"
      solveButton: false

tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
  # - name: gitea
  #   url: https://gitea-${guid}.${domain}/
  - name: Cloud (Azure)
    url: /cloud
